### ISSUE TITLE
Ensure reposense detects code correctly

### ISSUE THREAD

**Issue by triger15** [CS2103-AY1819S1-T16-2/main#63]
See nus-cs2103-AY1819S1/forum/issues/74.

Some contributions are not attributed correctly.
Need to add `_reposense/config.json` to root directory.

**Comment by triger15** [comment]
Please edit https://github.com/CS2103-AY1819S1-T16-2/main/blob/master/_reposense/config.json to update your display name and additional author names (if any).

**Comment by Caephler** [comment]
Would it make sense to ignore mass name refactoring commits? I think that's the main reason for wrongly attributed code. I think wenshei and I both did such commits that basically did a codebase wide change which might end up attributing code wrongly. Alternatively we can use `@@author` tags for such portions.

**Comment by triger15** [comment]
Hmm, can the refactoring commits be easily ignored? Perhaps we should wait for the next reposense report to be generated and check our own commit history before deciding on the next step. Otherwise using `@@author` would work too.

**Comment by Caephler** [comment]
Yeah, I looked through their page, we just have to find the commit hash and list it in some property in config.json. But yeah, sure we can wait and see before doing anything like that.

**Comment by Caephler** [comment]
Should be okay for now. Will re-open if there are any further issues.
