### ISSUE TITLE
As a TA, I want to add attendance for my students so that I can know whether my students are coming to tutorials.

### ISSUE THREAD

**Issue by triger15** [CS2103-AY1819S1-T16-2/main#96]
Introduce a `create-attendance` command for creating an attendance session for a specific tutorial group, as well as a `mark-attendance` command for marking attendances of students in a particular attendance session.
Marking students' attendance and creating of attendance sessions for a tutorial group should be decoupled as the TA may want to create the attendance session first before marking the attendance of students, or he/she may want to mark some specific students after the attendance session has been created.

**Arguments**:

For `create-attendance`:
- `tutorial-group-id` required
- `name` required

For `mark-attendance`:
- `tutorial-group-id` required
- `name` required
- `student-id` required, can have more than one

**What should be executed**:
For `create-attendance`:
An individual, unique session should be created for the particular tutorial group, that will contain a collection of students' attendance. There can be multiple attendance sessions within each tutorial group, to reflect the weekly attendance lists for each class.

For `mark-attendance`:
Students who belong in the tutorial group should have their attendance marked as present, and this should be reflected in the session created by `create-attendance`. TAs should be able to mark the attendance of multiple students at once.

**This action**:
Should affect the undo / redo history
Should make changes to the XML file

**Comment by Caephler** [comment]
#97 `create-attendance` done. Remaining work pushed to v1.4.
